PG_HOST: mellior.ru
PG_PORT: 5432
PG_USERNAME: tx
PG_PASSWORD: xkkmm2hhssss0d
PG_DATABASE: tx_2

TELEGRAM_TOKEN: 127746074:AAGD5aDG02m2DndUZZMB_J6MyC5FEBoVNQ4
TELEGRAM_WEBHOOK_URL: https://localhost:8080
